version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=teambalance
  server:
    depends_on:
      - postgres
    build:
      context: ./server
    ports:
      - '8080:8080'
    environment:
      - PGHOST=postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - '/app/node_modules'
      - './client:/app'
    ports:
      - '4200:4200'