version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=teambalance
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - '8080:8080'
    environment:
      - PGHOST=postgres
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client_react
    volumes:
      - '/app/node_modules'
      - './client_react:/app'
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
